version: '3'
services:
 freeradius:
  build:
     context: ./freeradius
     dockerfile: Dockerfile
  ports:
    - "1812:1812"
    - "1813:1813"
  container_name: vaaa_server
  networks:
    net:
       ipv4_address: 172.21.0.7

networks:
   net:
       driver: bridge
       ipam:
           driver: default
           config:
             - subnet: 172.21.0.0/16
