FROM ubuntu:latest


# define interface names (should be the same as in VNFD)
#ENV IFIN input
#ENV IFOUT output


#RUN apt-get update && \
#	apt-get install -y net-tools git iproute2 iputils-ping nano vim curl 

#COPY raddb/ /etc/raddb/
#EXPOSE 1812/udp 1813/udp
#EXPOSE 1812 1813

#ADD start.sh start.sh
#RUN chmod +x start.sh
#ADD stop.sh stop.sh
#RUN chmod +x stop.sh

RUN mkdir /tngbench_share

